letter_images = [
    {"letter": "a", "images": ['./assets/images/animals/arraia.jpg', './assets/images/animals/zebra.jpg', './assets/images/animals/cavalo.jpg', './assets/images/animals/leao.jpg' ,'./assets/images/animals/coruja.jpg', './assets/images/animals/crocodilo.jpg', './assets/images/animals/dinossauro.jpg', './assets/images/animals/elefante.jpg', './assets/images/animals/gato.jpg', './assets/images/animals/macaco.jpg', './assets/images/animals/passaro.jpg', './assets/images/animals/pato.jpg', './assets/images/animals/sapo.jpg', './assets/images/animals/tubarao.jpg', './assets/images/animals/veado.jpg', './assets/images/animals/zebra.jpg']},
    {"letter": "b", "images": ['./assets/images/animals/zebra.jpg']},
    {"letter": "c", "images": ['./assets/images/animals/cavalo.jpg', './assets/images/animals/coelho.jpg', './assets/images/animals/coruja.jpg', './assets/images/animals/crocodilo.jpg', './assets/images/animals/macaco.jpg']},
    {"letter": "d", "images": ['./assets/images/animals/dinossauro.jpg', './assets/images/animals/veado.jpg']},
    {"letter": "e", "images": ['./assets/images/animals/elefante.jpg', './assets/images/animals/leao.jpg', './assets/images/animals/peixe.jpg', './assets/images/animals/zebra.jpg']},
    {"letter": "f", "images": ['./assets/images/animals/elefante.jpg', './assets/images/animals/golfinho.jpg']},
    {"letter": "g", "images": ['./assets/images/animals/gato.jpg', './assets/images/animals/golfinho.jpg', './assets/images/animals/pinguim.jpg']},
    {"letter": "h", "images": ['./assets/images/animals/golfinho.jpg']},
    {"letter": "i", "images": ['./assets/images/animals/crocodilo.jpg', './assets/images/animals/dinossauro.jpg', './assets/images/animals/golfinho.jpg', './assets/images/animals/pinguim.jpg']},
    {"letter": "j", "images": ['./assets/images/animals/coruja.jpg']},
    {"letter": "l", "images": ['./assets/images/animals/cavalo.jpg', './assets/images/animals/coelho.jpg', './assets/images/animals/coruja.jpg', './assets/images/animals/crocodilo.jpg', './assets/images/animals/golfinho.jpg', './assets/images/animals/leao.jpg']},
    {"letter": "m", "images": ['./assets/images/animals/macaco.jpg']},
    {"letter": "n", "images": ['./assets/images/animals/dinossauro.jpg', './assets/images/animals/elefante.jpg', './assets/images/animals/golfinho.jpg', './assets/images/animals/pinguim.jpg']},
    {"letter": "o", "images": ['./assets/images/animals/cavalo.jpg', './assets/images/animals/coelho.jpg', './assets/images/animals/coruja.jpg', './assets/images/animals/crocodilo.jpg', './assets/images/animals/dinossauro.jpg', './assets/images/animals/gato.jpg', './assets/images/animals/golfinho.jpg', './assets/images/animals/leao.jpg', './assets/images/animals/macaco.jpg', './assets/images/animals/passaro.jpg', './assets/images/animals/pato.jpg', './assets/images/animals/tubarao.jpg', './assets/images/animals/veado.jpg']},
    {"letter": "p", "images": ['./assets/images/animals/passaro.jpg', './assets/images/animals/pato.jpg', './assets/images/animals/peixe.jpg', './assets/images/animals/pinguim.jpg', './assets/images/animals/sapo.jpg']},
    {"letter": "r", "images": ['./assets/images/animals/arraia.jpg', './assets/images/animals/coruja.jpg', './assets/images/animals/crocodilo.jpg', './assets/images/animals/dinossauro.jpg', './assets/images/animals/passaro.jpg', './assets/images/animals/tubarao.jpg', './assets/images/animals/zebra.jpg']},
    {"letter": "s", "images": ['./assets/images/animals/dinossauro.jpg', './assets/images/animals/passaro.jpg', './assets/images/animals/sapo.jpg']},
    {"letter": "t", "images": ['./assets/images/animals/elefante.jpg', './assets/images/animals/gato.jpg', './assets/images/animals/pato.jpg', './assets/images/animals/tubarao.jpg']},
    {"letter": "u", "images": ['./assets/images/animals/coruja.jpg', './assets/images/animals/crocodilo.jpg', './assets/images/animals/dinossauro.jpg', './assets/images/animals/tubarao.jpg']},
    {"letter": "v", "images": ['./assets/images/animals/cavalo.jpg', './assets/images/animals/veado.jpg']},
    {"letter": "x", "images": ['./assets/images/animals/peixe.jpg']},
    {"letter": "z", "images": ['./assets/images/animals/zebra.jpg']}
]

curiosities = [
    {"text": "Esse animal é conhecido por sua capacidade de voar e costuma ser visto em bandos.", "answer": "PASSARO"},
    {"text": "Esse animal é famoso por sua habilidade de saltar grandes distâncias.", "answer": "SAPO"},
    {"text": "Este animal é um dos mais altos e se alimenta de folhas de árvores altas.", "answer": "GIRAFA"},
    {"text": "Este animal vive tanto na água quanto em terra firme e tem uma casca dura para proteção.", "answer": "TARTARUGA"},
    {"text": "Esse animal é muito inteligente e gosta de viver em grupos organizados.", "answer": "GOLFINHO"},
    {"text": "Este animal é conhecido por seu forte rugido e é chamado de rei da selva.", "answer": "LEAO"},
    {"text": "Este inseto produz um alimento doce e muito apreciado pelo ser humano.", "answer": "MEL"},
    {"text": "Esse animal é capaz de mudar a cor da pele para se camuflar.", "answer": "CAMALEAO"},
    {"text": "Este animal tem uma longa tromba que utiliza para pegar alimentos e beber água.", "answer": "ELEFANTE"},
    {"text": "Este animal é conhecido por sua capacidade de cavar tocas na terra.", "answer": "TATU"},
    {"text": "Este pássaro noturno possui uma visão aguçada e é conhecido pelo seu pio característico.", "answer": "CORUJA"},
    {"text": "Esse animal vive em colônias e possui uma rainha que coordena o grupo.", "answer": "FORMIGA"},
    {"text": "O leite produzido por esse animal é muito consumido em várias culturas ao redor do mundo.", "answer": "VACA"},
    {"text": "Esse animal é um réptil conhecido por sua pele escamosa e pela habilidade de nadar.", "answer": "CROCODILO"},
    {"text": "Esse animal possui um veneno potente e se desloca com rapidez na água.", "answer": "RAIA"},
    {"text": "Este animal aquático é conhecido por fazer acrobacias e saltos fora da água.", "answer": "GOLFINHO"},
    {"text": "Este animal tem um casco forte que o protege contra predadores.", "answer": "TARTARUGA"},
    {"text": "Esse animal possui penas coloridas e pode aprender a imitar sons.", "answer": "PAPAGAIO"},
    {"text": "Esse animal voador é responsável pela polinização de várias plantas.", "answer": "ABELHA"},
    {"text": "Esse grande animal africano tem chifres e pode ser perigoso quando se sente ameaçado.", "answer": "BUFALO"},
    {"text": "Esse animal possui uma cauda grande e é excelente saltador, usando a cauda para equilíbrio.", "answer": "CANGURU"},
    {"text": "Esse animal tem bigodes sensíveis que o ajudam a detectar presas e obstáculos no escuro.", "answer": "GATO"},
    {"text": "Essas aves migratórias voam longas distâncias para fugir do frio.", "answer": "GANSO"},
    {"text": "Este animal vive em rios e possui dentes afiados para se alimentar de carne.", "answer": "JACARE"},
    {"text": "Este animal marinho é conhecido por sua grande inteligência e por viver em grupos.", "answer": "BALEIA"},
    {"text": "Esses insetos trabalham juntos para construir colmeias complexas.", "answer": "ABELHAS"},
    {"text": "Este animal produz uma lã muito utilizada para fabricação de roupas.", "answer": "OVELHA"},
    {"text": "Este animal vive na água, mas respira através de pulmões.", "answer": "PEIXEBOI"},
    {"text": "Esse animal possui penas impermeáveis que o ajudam a se manter seco.", "answer": "PATO"},
    {"text": "Este animal, símbolo da paz, é conhecido por sua cor branca e voo gracioso.", "answer": "POMBA"},
    {"text": "Este animal possui garras afiadas e uma habilidade incrível de escalar árvores.", "answer": "GATO"},
    {"text": "Esses animais têm uma memória excelente e podem reconhecer humanos e locais.", "answer": "ELEFANTES"},
    {"text": "Este animal, famoso por sua velocidade, caça em grupos e vive em savanas.", "answer": "LEOPARDO"},
    {"text": "Esses animais herbívoros têm uma dieta composta majoritariamente de folhas e galhos.", "answer": "VEADO"},
    {"text": "Esse animal marinho possui barbatanas que o ajudam a nadar de forma eficiente.", "answer": "TUBARAO"},
    {"text": "Este pequeno roedor é conhecido por armazenar alimentos em suas bochechas.", "answer": "HAMSTER"},
    {"text": "Este animal possui um casaco espesso para sobreviver em regiões frias.", "answer": "LOBO"},
    {"text": "Este animal é conhecido por sua habilidade de nadar e por ter uma longa cauda.", "answer": "SUCURI"},
    {"text": "Esse animal é muito adorado por seu canto e suas cores vibrantes.", "answer": "CANARIO"},
    {"text": "Este animal africano é conhecido por seu pescoço longo e por comer folhas de árvores.", "answer": "GIRAFA"},
    {"text": "Este animal é notável por seu couro espesso e chifres curtos.", "answer": "HIPOPOTAMO"},
    {"text": "Este animal tem uma crista na cabeça e é famoso por seu canto ao amanhecer.", "answer": "GALO"},
    {"text": "Este animal, famoso por sua velocidade, pode atingir até 100 km/h em corridas curtas.", "answer": "GUEPARDO"},
    {"text": "Este animal voa grandes distâncias e é símbolo de liberdade.", "answer": "AGUIA"},
    {"text": "Este animal tem um faro apurado e é usado em atividades de caça.", "answer": "CACHORRO"},
    {"text": "Este animal, com sua grande envergadura de asas, é capaz de voar em altitudes elevadas.", "answer": "CONDOR"},
    {"text": "Esse animal é capaz de mudar de cor para se camuflar em seu ambiente.", "answer": "POLVO"},
    {"text": "Este animal possui um bico curvado que o ajuda a abrir frutas e sementes.", "answer": "PAPAGAIO"},
    {"text": "Este animal constrói tocas subterrâneas e é ativo durante a noite.", "answer": "TAMANDUA"},
    {"text": "Esse produto é muito utilizado na culinária e é feito pelas abelhas.", "answer": "MEL"},
    {"text": "Usado por muitos animais para proteger e alimentar seus filhotes.", "answer": "LEITE"},
    {"text": "Os pássaros utilizam esse material para construir seus ninhos.", "answer": "GRAMA"},
    {"text": "Esse material, produzido por ovelhas, é utilizado para fazer roupas quentes.", "answer": "LA"},
    {"text": "Essa substância ajuda os peixes a respirar debaixo d'água.", "answer": "OXIGENIO"},
    {"text": "Os animais herbívoros se alimentam principalmente deste tipo de planta.", "answer": "CAPIM"},
    {"text": "Essa parte do corpo dos gatos ajuda a detectar movimentos e objetos no escuro.", "answer": "BIGODES"},
    {"text": "Esse elemento é essencial para a sobrevivência dos animais aquáticos.", "answer": "AGUA"},
    {"text": "Este material, encontrado em ovos, fornece nutrientes para o desenvolvimento de filhotes.", "answer": "GEMA"},
    {"text": "Essa estrutura nos pássaros é composta de queratina e permite o voo.", "answer": "PENAS"},
    {"text": "Essa parte do corpo é usada por muitos animais como uma forma de defesa.", "answer": "GARRAS"},
    {"text": "Este material é produzido por alguns insetos para criar suas casas ou armadilhas.", "answer": "SEDA"},
    {"text": "É uma fonte de energia importante para animais que se alimentam de plantas.", "answer": "AMIDO"},
    {"text": "Este órgão é usado por animais para sentir cheiros e identificar presas ou parceiros.", "answer": "NARIZ"},
    {"text": "Muitos animais produzem esta substância para ajudar na digestão dos alimentos.", "answer": "SALIVA"},
    {"text": "Usado por animais marinhos para flutuar e se deslocar na água.", "answer": "BARBATANA"},
    {"text": "Os animais usam isso para proteger seus olhos de sujeiras e luz intensa.", "answer": "PALPEBRA"},
    {"text": "Essa parte da anatomia dos peixes permite sua movimentação na água.", "answer": "NADADEIRA"},
    {"text": "Essa substância é responsável pelo revestimento das penas e pelo brilho de alguns animais aquáticos.", "answer": "OLEO"},
    {"text": "É uma cobertura natural que protege a pele dos animais de ambientes frios.", "answer": "GORDURA"},
    {"text": "Usado por muitas aves para atrair parceiros durante o acasalamento.", "answer": "CANTO"},
    {"text": "Esses pequenos cristais são utilizados por alguns animais marinhos para endurecer suas conchas.", "answer": "CALCIO"},
    {"text": "Esses resíduos de animais são essenciais para a fertilização do solo.", "answer": "ESTERCO"},
    {"text": "Este tecido permite que animais como macacos segurem objetos e se locomovam nas árvores.", "answer": "DEDOS"},
    {"text": "É uma proteína que compõe a pele, unhas e pelos dos animais.", "answer": "COLAGENO"},
    {"text": "Essa estrutura permite que algumas aves e peixes mantenham o equilíbrio durante o movimento.", "answer": "CAUDA"},
    {"text": "Este pigmento é responsável pela coloração dos pelos e penas de muitos animais.", "answer": "MELANINA"},
    {"text": "Essa cobertura natural protege alguns répteis e peixes de predadores.", "answer": "ESCAMAS"},
    {"text": "Essa substância pegajosa é usada por animais para construir abrigos e capturar presas.", "answer": "SECRECAO"},
    {"text": "Esses pequenos órgãos ajudam animais a capturar partículas de alimento na água.", "answer": "BARBAS"},
    {"text": "Essa estrutura óssea ajuda muitos animais a proteger seu cérebro e órgãos vitais.", "answer": "CRANIO"},
    {"text": "Os mamíferos possuem esse tipo de glândula que produz leite para seus filhotes.", "answer": "MAMARIA"},
    {"text": "Os pêlos dos mamíferos podem ficar arrepiados devido a esse estímulo involuntário.", "answer": "FRIO"},
    {"text": "Essa substância ajuda a curar feridas e é produzida naturalmente por alguns animais.", "answer": "COAGULO"},
    {"text": "Este material, produzido por alguns animais, é usado para marcar território.", "answer": "URINA"},
]
